### ISSUE TITLE
CMD.EXE was started in UNC path error message

### ISSUE THREAD

**Issue by BlaM** [AtomLinter/linter-php#221]
Not sure why this started to appear now - maybe connected to latest Atom Update. But in Windows I suddenly get this error message with a project that is located on a network share:

    Error: '\brain\tuxdev\[redacted]\[redacted]\em-ww' CMD.EXE was started with the above path as the current directory. UNC paths are not supported. Defaulting to Windows directory.

    Error: '\\brain\tuxdev\[redacted]\[redacted]\em-ww'
    CMD.EXE was started with the above path as the current directory.
    UNC paths are not supported.  Defaulting to Windows directory.
        at ChildProcess.<anonymous> (C:\Users\ddeobald\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:56:20)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:191:7)
        at maybeClose (internal/child_process.js:852:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Best guess (and just a guess): Atom now defaults to the project directory as working directory and linter-php uses CMD.EXE to run PHP?

**Comment by OHM79** [comment]
Same here.

**Comment by Arcanemagus** [comment]
What version of Atom are you running? It sounds like you are running into the UNC path issue fixed in v1.12.4.

**Comment by OHM79** [comment]
My Atom version v1.12.4
I tried but it was no good.

**Comment by BlaM** [comment]
Looks like that did not fix but create the issue for linter-php (a.k.a. it appeared somewhere around version 1.12.4)

**Comment by BlaM** [comment]
Still there with 1.12.7

**Comment by Arcanemagus** [comment]
What version of Windows are you all on? @daruma8 reported Windows 10 over in #232.

**Comment by BlaM** [comment]
Both Windows 8.1 and Windows 10, but I'll have to reinstall the package to see of the problem still appears.

**Comment by Arcanemagus** [comment]
Managed to replicate this while trying to figure out what was wrong in #250.

I'm not sure if there is anything that can be done about this since `cmd.exe` is notoriously bad about handling network paths. You can easily work around this by mapping a network drive and opening the code from there.

**Comment by Arcanemagus** [comment]
It looks like this isn't really possible to support: http://support.microsoft.com/kb/156276

That article lists a registry entry you can modify to disable the check, but strongly warns against doing so. The recommended way of working around this is to map a drive to the folder as mentioned already.
